### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/uno-material-ui#120]
SnackbarContextProvider doesn't exits anymore, remove from the documentation.

![image](https://user-images.githubusercontent.com/26309079/67334455-c8808780-f4e7-11e9-9362-9e13114acedb.png)

**Comment by geoperez** [comment]
Done!

**Comment by geoperez** [comment]
Sorry but this is still wrong. @MarcoLPR you need to modify the documentation project too.

Also, can you include the documentation of `Snackbarcontainer`. Ask to @kadosh for information.

**Comment by geoperez** [comment]
Just update the README file please with the new code.

**Comment by geoperez** [comment]
@kadosh can you talk with Choy about this issue?
