### ISSUE TITLE
Remove theme from the components

### ISSUE THREAD

**Issue by MarcoLPR** [unosquare/uno-material-ui#28]
It seems that it cannot be used Theme props in the components because they doesn't have a Theme.

For example:
![image](https://user-images.githubusercontent.com/25437790/59519436-78d0e600-8e8d-11e9-810a-83476d5a43d6.png)

This error occurs when I tried to use MenuList component, even with a Theme wrapping my app.

**Comment by geoperez** [comment]
Status?

**Comment by MarcoLPR** [comment]
I think that it's good to go, the theme-dependant components are problematic, this will decrease customization but it will make them more reliable.
