### ISSUE TITLE
ErrorBoundary Test

### ISSUE THREAD

**Issue by MarcoLPR** [unosquare/uno-material-ui#81]
Right now, I couldn't create an ErrorBoundary test because this component is a class that uses a HOC (withStyles)
Enzyme doesn't support the function setState on HOCs.
We will need to create a non-styled variant of ErrorBoundary to make the test or wait until React provide a componentDidCatch hook to make it a function instead of a class.

**Comment by MarcoLPR** [comment]
https://stackoverflow.com/questions/55266641/shallowwrappersetstate-can-only-be-called-on-class-components

**Comment by geoperez** [comment]
Let ignore this test for now.
