### ISSUE TITLE
TextValidator tests

### ISSUE THREAD

**Issue by MarcoLPR** [unosquare/uno-material-ui#82]
TextValidator tests throw several errors:
![image](https://user-images.githubusercontent.com/25437790/64204455-6a2a1780-ce5b-11e9-83ff-612c6ede51b2.png)

![image](https://user-images.githubusercontent.com/25437790/64204486-7dd57e00-ce5b-11e9-9d6b-eb846b732f34.png)

**Comment by geoperez** [comment]
Can you help me @kadosh ?

**Comment by kadosh** [comment]
Fixed at https://github.com/unosquare/uno-material-ui/pull/84. Please confirm it is working for you @MarcoLPR so that we can close this.
